### PR TITLE
Add loop param for videofile

### PR DESCRIPTION
**Pull request by iory**
This PR adds a loop rosparam for videofile.
if ```loop``` is true, this node keeps publishing image all the time.

### CODE REVIEW

**Comment by Carter12s** [comment]
Asking for a bump on merging this!

**Comment by awesomebytes** [comment]
Hello @iory. Sorry for the long delay. I'd gladly merge your changes but I need you to update the documentation too.

But first I would like to ask you if you can change the parameter name from `loop` to `loop_videofile` to make even more clear what it does.

That implies updating with your `loop_videofile` param:
* The README
  * The example usage launch file
  * The Parameters section
* The ROS wiki page: http://wiki.ros.org/video_stream_opencv with the same info (even tho I maybe should drop maintaining that and just point to the repo README...)

Thank you a lot for your PR tho!

**Comment by iory** [comment]
Thank you for your response!
I modified variable name `loop` to `loop_videofile` and also add launch file and README's comment and roswiki page.
Please check it.

**Comment by awesomebytes** [comment]
Merged, thank you :) I'm going to check out another PR and I'll re-release the package soon.

**Comment by iory** [comment]
Thank you!

**Pull request merged**
