### PR TITLE
Enable CI

### PR DESCRIPTION
**Pull request by furushchev**
This PR adds `.travis.yml` to enable CI.
https://github.com/ros-industrial/industrial_ci is used to test this package.

@awesomebytes
Could you enable testing on travis for this package?

### CODE REVIEW

**Comment by awesomebytes** [comment]
Hello, @furushchev 

Thanks for the multiple PRs, I'll enable the CI, but before, I'd like to know what is it actually running?

There are no tests in the package (unfortunately). Is it only compiling the package? I'm not familiar with industrial_ci.

**Comment by furushchev** [comment]
@awesomebytes Thanks for the comment!
By using `industrial_ci` we can check this package can be built successfully and all tests are passed on both devel and install space.
Exactly, we now have no test file in this package, it only checks if all the sources are built without error or not as for now.
I'll add some tests in minimum cases when I have time. :+1:

**Comment by furushchev** [comment]
@awesomebytes I added test files for some cases and all tests are passed.
https://github.com/ros-drivers/video_stream_opencv/blob/d9747e98800330c7cb16b16ab585d161893a2fe2/CMakeLists.txt#L47-L49

**Comment by awesomebytes** [comment]
Oh man, thank you so much! That's just great work!

**Comment by furushchev** [comment]
@awesomebytes Could you merge this PR first? It seems travis is already enabled on this repository. And then let's go forward to the other PRs. :+1:

**Comment by awesomebytes** [comment]
@furushchev Done!

**Comment by furushchev** [comment]
@awesomebytes Thank you very much for iterating and merging! Could you add me to maintainers as well to help you with mergiing other PRs if you don't mind. :)

**Comment by awesomebytes** [comment]
@furushchev You have an invite

**Comment by furushchev** [comment]
@awesomebytes Great! Thanks again! :+1:

**Pull request merged**
