### PR TITLE
Add option to set resolution of video stream.

### PR DESCRIPTION
**Pull request by wiebevr**
Add an option to set the resolution of the video stream using the CV_CAP_PROP_FRAME parameters. I needed this to be able to use the full angle of view of a camera with an aspect ratio of 16:9.

Thought this would be useful to have.

### CODE REVIEW

**Comment by awesomebytes** [comment]
Awesome!

**Comment by wiebevr** [comment]
Thanks!

**Comment by awesomebytes** [comment]
@wiebevr I've made a few more changes (to make optional the width and height). I've also tried it myself and it works. Also did a bit of cleanup of prints and so. Updated the license to BSD... and made a release for indigo! (well, it's here https://github.com/ros/rosdistro/pull/13198)
If it goes well I guess I'll try on jade and kinetic.

**Comment by wiebevr** [comment]
Nice, thanks!

**Pull request merged**
