### PR TITLE
Added rate limiting to camera_fps_rate also if videofile is used as input

### PR DESCRIPTION
**Pull request by aviogit**
Also added dummy <?xml version="1.0"?> headers in launchfiles to make VIM apply syntax highlighting.

### CODE REVIEW

**Comment by awesomebytes** [comment]
If you fix the ros::Rate thing, I like the addition :)

**Comment by aviogit** [comment]
Eheh what's wrong with that ros::Rate? It's because it's alloc'd inside a conditional block?

**Comment by awesomebytes** [comment]
@aviogit Yeah, I mean, you allocate a new ros::Rate object, on every iteration, to sleep once on it, then it gets destroyed, and so on, all the time. Just  create it beforehand conditionally. And use the sleep conditionally.

**Comment by aviogit** [comment]
It's a matter of readability of the code vs. performance. IMHO the impact on performance is negligible here, especially if one compiles with -On (I could bet that with -O2 the impact on performance is exactly zero). On the contrary, ros::Rate has no default constructor and set_camera_fps acquires its value only after parameter initalization, so I should create a global pointer to ros::Rate and take the address after parameter init and in do_capture() test if it's null, and so on.

Do you have a better way to do this stuff? I'm just seeing bad things coming from this route :)

**Comment by awesomebytes** [comment]
I'd just move the declaration of ros::Rate out of the loop, I see no point on recreating a new object to just sleep once on it.

**Comment by aviogit** [comment]
Oops, sorry, you're right, it can be moved out of the loop. I'll try to resubmit the pull request...

**Pull request closed without merging**
